### ISSUE TITLE
【bug】Topbar 在 dock 处于 fashion mode 的时候相互遮罩

### ISSUE THREAD

**Issue by spencerwooo** [justforlxz/deepin-topbar#105]
![image](https://user-images.githubusercontent.com/32114380/47638313-32967300-db99-11e8-94e5-1c38fdb1e2b2.png)

问题如描述。

系统：Manjaro Linux 18.0.0
DDE: 15.7 Desktop

**Comment by justforlxz** [comment]
0.5.1包含了简单的处理，已经不会重叠了。
![image](https://user-images.githubusercontent.com/12298476/48753315-842dab80-ecc8-11e8-9fef-bc4144c27d4e.png)
