### ISSUE TITLE
No icons or modules

### ISSUE THREAD

**Issue by InvisibleRasta** [justforlxz/deepin-topbar#110]
https://anonfile.com/005eL9l6bb/deepin-screen-recorder_Select_area_20181123034455_gif
as the picture shows i have no options in the settings and no tray icons showup. 
running archlinux

**Comment by justforlxz** [comment]
Setting the blank is a bug that is still unprocessed. last switch is the tray, and you need logout after closing.

**Comment by Byteron** [comment]
I have the same issue, not sure how to solve it. 
Also, whenever I log out or restart, the topbar disappears and I have to manually start the program to have it show up.

**Comment by rechless** [comment]
Exactly the same issue!
