### ISSUE TITLE
not transparent and the tray not work.

### ISSUE THREAD

**Issue by amaothree** [justforlxz/deepin-topbar#116]
System:
-----

OS: Archlinux 
Kernal: 4.19.12.arch1-1
Topbar Ver.: 0.6.0-1

Issues:
-----

1. The top bar can't be transparent everytime .
2. The system tray not work and it checked in the setting.

Screenshot:
-----
![deepinscreenshot_desktop_20181223233521](https://user-images.githubusercontent.com/26244249/50385171-9c4f7b00-070b-11e9-8d62-8810e746e263.png)

**Comment by justforlxz** [comment]
I tried it this morning and didn't reproduce the problem.

**Comment by amaothree** [comment]
The topbar is transparent at it start, then I enter the menu, it be black, but it won't change to transparent again when I quit the menu.
I try to record a gif.


![deepin-screen-recorder_select area_20181224150011](https://user-images.githubusercontent.com/26244249/50392824-a6fe2480-078c-11e9-8cad-5f6fbeabfb00.gif)

**Comment by amaothree** [comment]
The system-tray I solved, just uncheck "enable the dock tray", the topbar tray back.

**Comment by amaothree** [comment]
This issue is still in the new version.

**Comment by amaothree** [comment]
I solved this issue by use the modsetting driver instead the DDX intel driver.

**Comment by MordragT** [comment]
Got the same issue dock stays black
