### ISSUE TITLE
编译错误

### ISSUE THREAD

**Issue by yanke1311** [justforlxz/deepin-topbar#118]
/home/yanke/Downloads/deepin-topbar-0.6.0/src/frame/mainframe.cpp:215:69: error: ‘class Dtk::Widget::DWindowManagerHelper’ has no member named ‘currentWorkspaceWindowIdList’; did you mean ‘currentWorkspaceWindows’?
     QVector<quint32> windowList = DWindowManagerHelper::instance()->currentWorkspaceWindowIdList();
                                                                     ^~~~~~~~~~~~~~~~~~~~~~~~~~~~
                                                                     currentWorkspaceWindows
make[2]: *** [src/CMakeFiles/deepin-topbar.dir/build.make:366：src/CMakeFiles/deepin-topbar.dir/frame/mainframe.cpp.o] 错误 1
make[1]: *** [CMakeFiles/Makefile2:87：src/CMakeFiles/deepin-topbar.dir/all] 错误 2
make: *** [Makefile:130：all] 错误 2

**Comment by justforlxz** [comment]
需要dtk版本不能低于2.0.9.11

**Comment by aiamuzz** [comment]
@justforlxz ...

even i am unable to build ... facing the following error ...

```
CMake Error at /usr/share/cmake-3.11/Modules/FindPkgConfig.cmake:418 (message):
  A required package was not found
Call Stack (most recent call first):
  /usr/share/cmake-3.11/Modules/FindPkgConfig.cmake:585 (_pkg_check_modules_internal)
  src/CMakeLists.txt:265 (pkg_check_modules)


-- Configuring incomplete, errors occurred!
See also "/home/muz/Downloads/linuxPackagesBuildnInstall/deepin-topbar/deepin-topbar-0.6.0/Builld/CMakeFiles/CMakeOutput.log".

```

**Comment by justforlxz** [comment]
Can you provide a complete log, I need to know which package does not exist

aiamuzz <notifications@github.com> 于2018年12月25日周二 下午4:47写道：

**Comment by aiamuzz** [comment]
@justforlxz ...

ok i got past the above cmake error ... by installing `libdde-network-utils-dev`

however i am now facing a make error ...

```
/home/muz/Downloads/linuxPackagesBuildnInstall/deepin-topbar/deepin-topbar-0.6.0/src/frame/mainframe.cpp: In member function ‘void MainFrame::onWindowListChanged()’:
/home/muz/Downloads/linuxPackagesBuildnInstall/deepin-topbar/deepin-topbar-0.6.0/src/frame/mainframe.cpp:215:69: error: ‘class Dtk::Widget::DWindowManagerHelper’ has no member named ‘currentWorkspaceWindowIdList’; did you mean ‘currentWorkspaceWindows’?
     QVector<quint32> windowList = DWindowManagerHelper::instance()->currentWorkspaceWindowIdList();
                                                                     ^~~~~~~~~~~~~~~~~~~~~~~~~~~~
                                                                     currentWorkspaceWindows
make[2]: *** [src/CMakeFiles/deepin-topbar.dir/build.make:366: src/CMakeFiles/deepin-topbar.dir/frame/mainframe.cpp.o] Error 1
make[1]: *** [CMakeFiles/Makefile2:87: src/CMakeFiles/deepin-topbar.dir/all] Error 2
make: *** [Makefile:130: all] Error 2

```

**Comment by justforlxz** [comment]
> @justforlxz ...
> 
> ok i got past the above cmake error ... by installing `libdde-network-utils-dev`
> 
> however i am now facing a make error ...
> 
> ```
> /home/muz/Downloads/linuxPackagesBuildnInstall/deepin-topbar/deepin-topbar-0.6.0/src/frame/mainframe.cpp: In member function ‘void MainFrame::onWindowListChanged()’:
> /home/muz/Downloads/linuxPackagesBuildnInstall/deepin-topbar/deepin-topbar-0.6.0/src/frame/mainframe.cpp:215:69: error: ‘class Dtk::Widget::DWindowManagerHelper’ has no member named ‘currentWorkspaceWindowIdList’; did you mean ‘currentWorkspaceWindows’?
>      QVector<quint32> windowList = DWindowManagerHelper::instance()->currentWorkspaceWindowIdList();
>                                                                      ^~~~~~~~~~~~~~~~~~~~~~~~~~~~
>                                                                      currentWorkspaceWindows
> make[2]: *** [src/CMakeFiles/deepin-topbar.dir/build.make:366: src/CMakeFiles/deepin-topbar.dir/frame/mainframe.cpp.o] Error 1
> make[1]: *** [CMakeFiles/Makefile2:87: src/CMakeFiles/deepin-topbar.dir/all] Error 2
> make: *** [Makefile:130: all] Error 2
> ```

the DTK version need >= 2.0.9.11

**Comment by aiamuzz** [comment]
> the DTK version need >= 2.0.9.11


how do we do that ?

`sudo apt-get install libdtkcore2` lets us install only

**Comment by yanke1311** [comment]
I am also (2.0.9.10-1)

**Comment by justforlxz** [comment]
> I am also (2.0.9.10-1)

The new dtk and topbar will push updates this week, no need to compile.
