### ISSUE TITLE
Won't run on Arch Linux x86_64 (kernel 4.20.0-arch1-1-ARCH)

### ISSUE THREAD

**Issue by Pauligrinder** [justforlxz/deepin-topbar#126]
```
[pauli@Thermaltake ~]$ deepin-topbar
configPath "/home/pauli/.config/deepin/deepin-topbar/config.conf"
create config "/home/pauli/.config/deepin/deepin-topbar/config.conf"
Fontconfig warning: ignoring en_CUSTOM.UTF-8: not a valid region tag
QVariant DBusExtendedAbstractInterface::internalPropGet(const char*, void*) "This Extended DBus interface is not valid yet."
dbus[3505]: arguments to dbus_message_new_method_call() were incorrect, assertion "_dbus_check_is_valid_path (path)" failed in file dbus-message.c line 1366.
This is normally a bug in some application using the D-Bus library.

  D-Bus not built with -rdynamic so unable to print a backtrace
Aborted (core dumped)
```

And that's it. Please tell me what package versions could be relevant - there's too many deepin packages to list them all. The version of deepin-topbar is 0.6.2-1. This one is installed using pacman, but I also tried building it from source with same results.
I was able to run it once by putting the .desktop file in autostart, but then I only got a bunch of icons and text stacked in the top left corner with no menu to configure it or anything. And the next time I restarted it didn't work again.

**Comment by KonnorTimmons1297** [comment]
I'm experiencing the same issue as well on Arch.

**Comment by timothysnave** [comment]
I'm also experiencing this issue on Manjaro

**Comment by Pauligrinder** [comment]
I found the solution! deepin-topbar expects NetworkManager (daemon) to be running and if the connection fails, the whole thing fails. So install network-manager and then do sudo systemctl start NetworkManager, then topbar works :)
