### ISSUE TITLE
2 Monitor problem

### ISSUE THREAD

**Issue by mikield** [justforlxz/deepin-topbar#131]
There is a problem when I have 2 monitors plugged in.

Top bar appears on the main screen, but also takes space on top of the second screen, so I have exactly topbar size empty space on my second screen.

First Monitor:
![image](https://user-images.githubusercontent.com/4073672/51433278-7accab00-1c47-11e9-9996-98cb1da59f07.png)

Second Monitor: 
![image](https://user-images.githubusercontent.com/4073672/51433274-6ab4cb80-1c47-11e9-9fe2-e2ba6b2d5e6c.png)

**Comment by sanjeevkpandit** [comment]
Same here. Using Arch Linux.

**Comment by sanjeevkpandit** [comment]
It seems to happen when the external monitor is oriented on top of the primary screen. Along with the above issue, on the Primary Monitor, the title bar of the maximized window is overlapped by the top bar. But, everything seems to work normally when the external monitor is oriented to the right of the primary monitor.

Maximized window on primary monitor on top-bottom monitor alignment:
![image](https://user-images.githubusercontent.com/13619272/51815169-49a74700-22e7-11e9-82d6-6cc8b9a3b42b.png)

On left-right monitor alignment:
![deepinscreenshot_select-area_20190128103303](https://user-images.githubusercontent.com/13619272/51815347-5e380f00-22e8-11e9-8b65-fae932eb9f24.png)
![deepinscreenshot_select-area_20190128103314](https://user-images.githubusercontent.com/13619272/51815348-609a6900-22e8-11e9-91e5-adfda44b7be8.png)

**Comment by itsTyrion** [comment]
really strange. I'm using the arch based Manjaro Linux and I don't have this bug at all o_O

**Comment by sanjeevkpandit** [comment]
Is there any solution for it? Or, is there any kind of alternative application?
