### ISSUE TITLE
最新版本系统信息里的cpu占用和内存占用没有显示

### ISSUE THREAD

**Issue by wootifer** [justforlxz/deepin-topbar#143]
问题：如题所示，更新的feature里面提到可以显示CPU信息和内存信息，但是安装后却没有显示

截图：
![image](https://user-images.githubusercontent.com/26326251/55272261-d1fc9500-52f4-11e9-9f7d-afcb9a5c40e9.png)

**Comment by PikachuHy** [comment]
自己编译的，还是应用商店里装的？

**Comment by hbhgwtf** [comment]
> 自己编译的，还是应用商店里装的？

在应用商店里装的。

**Comment by PikachuHy** [comment]
> > 自己编译的，还是应用商店里装的？
> 
> 在应用商店里装的。

应用商店里的是老版本，要自己编译才能用新功能

**Comment by hbhgwtf** [comment]
OK，建议在topbar的设置中加个“关于”，然后把版本号加上去。

**Comment by Ashywhisper** [comment]
> > > 自己编译的，还是应用商店里装的？
> > 
> > 
> > 在应用商店里装的。
> 
> 应用商店里的是老版本，要自己编译才能用新功能

头疼，不会编译

**Comment by PikachuHy** [comment]
@Ashywhisper 
我打了个包，你可以自己下载
地址：https://github.com/PikachuHy/deepin-topbar/releases/tag/1
