### ISSUE TITLE
cant build from release package

### ISSUE THREAD

**Issue by Bearbobs** [justforlxz/deepin-topbar#144]
showing error DtkWidget
![DeepinScreenshot_Desktop_20190404215237](https://user-images.githubusercontent.com/21145870/55571893-0ffa1e80-5724-11e9-8830-9d939f7f88af.png)

**Comment by zhangqx1994** [comment]
hi 
you can see this and try it XD

[topbar-relese.sh.zip](https://github.com/justforlxz/deepin-topbar/files/3078257/topbar-relese.sh.zip)

**Comment by zhangqx1994** [comment]
> showing error DtkWidget
> ![DeepinScreenshot_Desktop_20190404215237](https://user-images.githubusercontent.com/21145870/55571893-0ffa1e80-5724-11e9-8830-9d939f7f88af.png)

hi you can see it and try

[topbar-relese.sh.zip](https://github.com/justforlxz/deepin-topbar/files/3078259/topbar-relese.sh.zip)

**Comment by zahar77735** [comment]
E: Could not find package libdtkbase-dev

**Comment by zhangqx1994** [comment]
> E: Could not find package libdtkbase-dev. Deepin 15.9.2

the new version fixed this 
try it :dancer:

**Comment by zjsxwc** [comment]
> > showing error DtkWidget
> > ![DeepinScreenshot_Desktop_20190404215237](https://user-images.githubusercontent.com/21145870/55571893-0ffa1e80-5724-11e9-8830-9d939f7f88af.png)
> 
> hi you can see it and try
> 
> [topbar-relese.sh.zip](https://github.com/justforlxz/deepin-topbar/files/3078259/topbar-relese.sh.zip)

thank you for the `topbar-relese.sh`, it's a good example!

currently `libdtkbase-dev` is not available in my `Deepin 15.10.1`.
so i used `libdtkwidget-dev` replaced `libdtkbase-dev` to build the program.
it works!

**Comment by Bearbobs** [comment]
solved
