### ISSUE TITLE
Topbar from deepin-repo has ugly shadow effect on the bottom. 

### ISSUE THREAD

**Issue by TylerHelt0** [justforlxz/deepin-topbar#160]
![DeepinScreenshot_select-area_20190719181130](https://user-images.githubusercontent.com/51061160/61570185-aee72400-aa50-11e9-87e7-b02f9f574e61.png)

**Comment by shiqingk** [comment]
这个是升级到deepin15.11后出现的问题，希望大佬能尽快修复

**Comment by yarecco** [comment]
I've built from sources it looks better... but still no transparency and when you watch something full screen on other workspace it just dissapers from any other workspace. 
![Zrzut ekranu Deepin_20190720115000](https://user-images.githubusercontent.com/29832803/61577214-8b6db900-aae4-11e9-9c82-92bba9e956d2.png)

**Comment by gaoyanglion** [comment]
附议，我也存在该问题

**Comment by yarecco** [comment]
For our Dear Friends from China, if you are able to read in English please reply in English too, for those who aren't lucky to live in China, plz :-) I am from Poland but didn't even think to post in Polish on Github.

**Comment by yarecco** [comment]
You can if you want replace deepin-topbar file from /usr/bin with this built from sources, it doen;t reproduce that ugly shadow as in the first post. (need to be unzipped and put into /usr/bin replacing the existing one but you need to disable topbar first)
If you want to get back the original file simply reinstall deepin-topbar from repository.
[deepin-topbar.zip](https://github.com/justforlxz/deepin-topbar/files/3413640/deepin-topbar.zip)

**Comment by aluisco** [comment]
I will try to build binary from sources and see because I don't like this shadow

**Comment by yarecco** [comment]
Yeah it doesn't look nice...  and the annoying thing is that fullscreen mode kills the topbar on other workspaces. It just dissappears.

**Comment by TylerHelt0** [comment]
Executable built form source works great. I suppose the deepin repos have an outdated version as their most recent.

**Comment by TylerHelt0** [comment]
Yes, this issue occured after upgrade.

**Comment by TylerHelt0** [comment]
Is there anyone on the deepin team I can alert about this? Its been a week now and now updates from the deepin repo.

**Comment by itsTyrion** [comment]
I also have that effect on Manjaro with deepin desktop. (I installed it from the official Arch/pacman community repo)
it says something with bad window id (I started it in terminal)

I guess that the deepin team changed something in the API that causes this bug in older versions (and deepin-topbar is outdated in the deepin repo + Archlinux repo)

**Comment by yarecco** [comment]
With new version built from sources (0.6.6) it's finally good working and looking
![backg](https://user-images.githubusercontent.com/29832803/62172015-3ece7d00-b331-11e9-9b69-ad6571a2da2f.png)
You can if you want replace deepin-topbar file from /usr/bin with this built from sources, it doesn't reproduce that ugly shadow as in the first post. (need to be unzipped and put into /usr/bin replacing the existing one but you need to disable topbar first)
If you want to get back the original file simply reinstall deepin-topbar from repository.

[deepin-topbar.zip](https://github.com/justforlxz/deepin-topbar/files/3449176/deepin-topbar.zip)

**Comment by ParrySMS** [comment]
感谢这位朋友 @yarecco ，确实能解决问题，但是国内下载很慢。我放一个国内的下载链接
Thanks, Bro!  It works but it takes a long time to download in China.  Here is a China server link to your file.  

deepin-topbar.zip  https://share.weiyun.com/5PQiVqM
