### ISSUE TITLE
Force quit action[Bug]

### ISSUE THREAD

**Issue by Jesterjke** [justforlxz/deepin-topbar#25]
Force quit action have a strange behavior:
1. Nauitilus  - acts as should
2. Spotify/VIvaldi - opens windows view(like when you scroll over the icon)
3. Opera - opens new incognito window(????????)
4. Deepin Terminal - opens weird version of terminal, which I was unable to close.

I would suggest you to simply call **xkill**, so user can decide which window he wants to close by force.

**Comment by kirigayakazushin** [comment]
Try it on deepin 15.5 beta.
