### ISSUE TITLE
error installing ...

### ISSUE THREAD

**Issue by aiamuzz** [justforlxz/deepin-topbar#31]
Hi,

```
E: The repository 'https://packages.mkacg.com panda Release' does no longer have a Release file.
N: Updating from such a repository can't be done securely, and is therefore disabled by default.
```

```
Err:1 https://packages.mkacg.com panda/main amd64 deepin-topbar amd64 0.3.5-1
  404  Not Found
E: Failed to fetch https://packages.mkacg.com/pool/main/d/deepin-topbar/deepin-topbar_0.3.5-1_amd64.deb  404  Not Found
E: Unable to fetch some archives, maybe run apt-get update or try with --fix-missing?

```

unable to install package ...

**Comment by kirigayakazushin** [comment]
The address of the reverse proxy server was changed incorrectly and has been fixed. Please try again.

**Comment by aiamuzz** [comment]
@kirigayakazushin ...

thanks ... was able to install.

about the deepin-topbar design ... can we discuss on a private channel ... preferable a chatting platform, on whichever chat platform you are active ?

**Comment by kirigayakazushin** [comment]
@aiamuzz  I'm sorry I haven't responded these days. Can be connected by telegram https://t.me/kirigayakazushin
