### ISSUE TITLE
Sytem Tray conflict ?

### ISSUE THREAD

**Issue by aiamuzz** [justforlxz/deepin-topbar#74]
Hi,

While i am testing the top-bar i noticed that the system tray contents work fine from the top-bar, however the same system-tray contents from the dde-dock do not open as intended ... 

Eg. : A bittorrent client is a regular on my system tray ... when 'topbar' is running i can't open the client from the dde-dock systray ... it opens only from the 'topbar'.

Is this a limitation that it can't be operated fro 2 places or is it by design to avoid a bigger issue or is it that something is amiss ?

PS : Why does the language switching entry in the dde-dock not show up in the topbar system tray ?

**Comment by kirigayakazushin** [comment]
In the latest topbars and docks, hidden dock trays have been supported, which can be enabled in the topbar settings.
The function of switching languages is not supported temporarily. This is a dedicated feature of the dock. I have not synchronized the code yet.

**Comment by aiamuzz** [comment]
> In the latest topbars and docks, hidden dock trays have been supported, which can be enabled in the topbar settings.
> The function of switching languages is not supported temporarily. This is a dedicated feature of the dock. I have not synchronized the code yet.

great !!! ... i like that topbar is evolving and adapting to the Deepin UI(glad you have decided to go that way) ... result is evident ... topbar has started to look more and more like an official deepin app.

What about the systray apps not opening from the dde-dock systray ?
They only open from the topbar systray ... is this a bug or both locations can't function simultaneously ?

**Comment by kirigayakazushin** [comment]
This involves a X11 problem, and is not handled well, so windows can only belong to a program, and the previous window will fail.
