### ISSUE TITLE
Text in settings is not visible.

### ISSUE THREAD

**Issue by Cdsi37** [justforlxz/deepin-topbar#91]
I can't read anything in settings. My system is Deepin 15.7. Deepin 15.6 had that issue too. I tried changing theme and font, that didn't help. Please fix it or at least provide a screenshot with readable text. Thanks.
![deepinscreenshot_deepin-topbar_20180823210329](https://user-images.githubusercontent.com/42325026/44543365-07fee880-a718-11e8-93db-103c29ec59f8.png)

**Comment by felixsrg** [comment]
I also have this problem with 15.7, can't really change anything.

**Comment by Kaiyoto** [comment]
+1

**Comment by Kaiyoto** [comment]
This is a major problem! You must fix this ASAP!
